// DB - Prisma 配置：定義 Prisma 客戶端和遷移設定

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma 7 現在規定把密碼連線設定放在這裡
    url: env("DATABASE_URL"),
  },
});


